# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               diesire
tagline:             'Personal site'
description:         'diesire Personal site'
url:                 http://diesire.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              diesire
  url:               https://twitter.com/diesire
  email:             diesire@gmail.com

# Custom vars
version:             0.0.1
